# Generated by Django 5.0.6 on 2024-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='die',
            old_name='value',
            new_name='value1',
        ),
        migrations.AddField(
            model_name='die',
            name='value2',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
